# Generated by Django 5.1.2 on 2025-06-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
    ]
